### ISSUE TITLE
Screen share volume?

### ISSUE THREAD

**Issue by dillfrescott** [edumeet/edumeet#1001]
Not for sure if its a bug, but is there a way to adjust the screen share audio independently from the user volume?

**Comment by N7Remus** [comment]
If you are sharing a video or music you can lower the volume on the track on the website (for example youtube) and that will lower the output volume too.

We are using the built in browser interface getDisplayMedia which does not have volume parameters, but it might be possible to change the volume on the shared track inside edumeet. I will look into it.

**Comment by DillFrescott** [comment]
Noted. The issue I am facing is that my friend and I have our computers at much different volumes due to different types of headsets. It would be nice to be able to use a volume slider to balance things out. That is basically my situation.

Just thought I'd include some context!

A volume on the track would be perfect! Looking forward to see if it can be done!

**Comment by havfo** [comment]
This is perfectly possible to do, in principle no different than the regular mic audio slider.

Client development is currently focused in the new edumeet-client repo though, so you may not see it here.

**Comment by DillFrescott** [comment]
Noted! Thank you!

**Comment by havfo** [comment]
Should be fixed in new client, if not please report there.
