### ISSUE TITLE
set an access code to the room

### ISSUE THREAD

**Issue by ThamerAlluqmani** [edumeet/edumeet#1087]
I saw in the project there is a feature for access code and join by access.
But how can I use this feature? 

Thanks

**Comment by N7Remus** [comment]
Access codes were an implementation so when you loose connection momentarily you do not lock yourself out of the room.
This functionality has been reworked since we have a management service.
If you configure the management service. You can login with a user that has permission for a specific room and set default permissions.
I have made more documentation on the edumeet-docker repo.
