### ISSUE TITLE
More shortcuts.... P for participants, F for full screen, C for chat, etc.

### ISSUE THREAD

**Issue by cap19** [edumeet/edumeet#357]
It would make life easy to have a few more shortcuts... especially for the participants drawer.

**Comment by L4ky** [comment]
To have full screen you can use standard F11 shortcut. This is a universal one.
Need to be mentioned on Help section.

I agree with:
- C for Chat
- F for File sharing
- P for Participants
- S for settings

**Comment by havfo** [comment]
I agree, those would be nice

**Comment by so010** [comment]
I think there exist at least two kinds of user-bubbles according to shortcuts.
In my humble opinion F is exclusively reserved for full-screen only ;)
It is there everywhere where video services are netflix, amazon video, youtube, ...
I use it a lot and I know many who do use this. People using F11 I know only a few technical persons. On most keyboards the function-key-row is double occupied with very useful other shortcuts because people don't use or know about original function keys. Additionally F11 breaks good user experience with our built in full screen function.

**Comment by havfo** [comment]
I didn't think about that, absolutely, F for fullscreen.

**Comment by cap19** [comment]
BTW, 1 and 2 keys are ingenious. When I'm bored in a meeting, I go 1,2... 1,2... 1,2   :-)

**Comment by so010** [comment]
Sounds like multiplayer-Tetris in mm ... just a thought ;)

**Comment by havfo** [comment]
Fixed in new client
