### ISSUE TITLE
press space to talk notificataion, so PTT without headset is disturbing!

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#430]
Not only local but also the remote voice activates this notification. 
We should disable it intelligently, or at least the user should be able to disable it!

**Comment by Astagor** [comment]
I think letting user disable it is enough. Non IT users tend to get confused when to much things happen automatically, so they would not understand why sometimes they get the message and sometimes they don't. But b this is only my opinion.

**Comment by so010** [comment]
This is only the case if your audio device has cross talking issue. Usually this is by echo-cancellation filters either from audio driver or because your browser runs aggressive echo-cancellation or (you have disable echo-cancellation AND your mic plugs up your speaker device). In each case I think user should see that this is happening.

**Comment by Astagor** [comment]
I thought @misi was talking about background noise, causing the PPT to appear. I can confirm what @so010 says, that with properly working echo cancelling, even if you use mic and speakers (not a headset), the PPT appears only when needed, so when you talk. At least I have not noticed, that it was appearing in a annoying way. I use a Jabra speaker/mic 90% of the time.

**Comment by misi** [comment]
It seems it was just my mistake and it is only behaves badly if there is something wrong with the user :)
or the user echo cancellation..
