### ISSUE TITLE
Listener only attendee

### ISSUE THREAD

**Issue by hhuseyinpay** [edumeet/edumeet#437]
Hi, currently there are two options in the lobby these are voice and voice+camera. Is it possible to enter the room as a listener? Or is it possible to give mic and camera permission to only moderators by default? So the moderator decides who can speak.

**Comment by so010** [comment]
It is planned a more sophisticated join dialog where you can chose your media you want to join with and just click >>Join<< 
Then users can join in whatever way they want.

**Comment by hhuseyinpay** [comment]
It would be awesome. But actually what I need is that permissions like SEND_CHAT or SHARE_SCREEN in permissionsFromRoles in the config file and simple join button in the Joindialog screen. I can implement this feature for my needs but I don't want to change codebase because you guys work hard :) If I make big changes, integrate new features from the master are gonna be painful for me.

**Comment by havfo** [comment]
I'm not sure I understand your need. You want to be able to chose permissions in the join dialog?

**Comment by hhuseyinpay** [comment]
In my use case, there will be 5 speakers(or presenter) and +500 listeners. But currently, all participant joins with mic and camera permission. I want normal participants can not open their mic or camera by default.

**Comment by havfo** [comment]
Aha, I understand. You need some new permissions, SHARE_AUDIO, SHARE_VIDEO, this sounds very reasonable.

**Comment by hhuseyinpay** [comment]
That's right.

**Comment by Alex-YddeR** [comment]
This is something most of the current requirements like panelist’s and audience. Panelist’s will be able to talk to each other and share presentations where are audience they are just watching/hearing the panelist’s. 

Currently most of the requirements are like this in any of the industry. Most webinar’s are done like this due to the current situation. Also in education sector trainer doesn’t want the users to be a as same role. 
There should be a role called listener who can only view only user, but host can enable based on the request.

**Comment by hhuseyinpay** [comment]
Exactly. @Alex-YddeR described the need very well.

**Comment by Astagor** [comment]
Works good, as far as I am concerned. But, now on JoinDialog.js the buttons might not make sense, as you join with audio and video button, but cannot turn it on. This is however NOT very important.

**Comment by havfo** [comment]
I thought about that, and I plan to change the behaviour a bit to make the buttons about the meeting in general, not exactly what you want to share. E.g. If you chose audio only, you receive only audio from everybody.

Any thoughts?

**Comment by Astagor** [comment]
Hmm, I think the users are used to joining and receiving everything that is being currently sent, so I think making them choose what the want to see, should be like an advanced option on joining, but default should be everything there is. Otherwise it would be to complected for a normal user. I like the buttons how they are now, just the JoinDialog is problematic right now, as we don't have information about the peer (for example what permission it has). I got positive feedback from users, that it is very easy to share a link and join a room, and I think we need to keep this this way. I think changes here need discussion.

**Comment by Alex-YddeR** [comment]
How do i enable/check this role?

**Comment by Astagor** [comment]
have a look at server/config/config.example.js you have
		// The role(s) have permission to share audio
		[SHARE_AUDIO]      : [ userRoles.NORMAL ],
		// The role(s) have permission to share video
		[SHARE_VIDEO]      : [ userRoles.NORMAL ],

**Comment by havfo** [comment]
@Alex-YddeR remember to import them in the top as well. Also remember that those are arrays of roles that have the permission. So you could do ex.:
`[SHARE_VIDEO] : [ userRoles.NORMAL, userRoles.PRESENTER ],`

**Comment by hhuseyinpay** [comment]
I think there should be a just Join button. simple and easy :)

**Comment by hhuseyinpay** [comment]
I couldn't find how to change user roles? There is a setting MODIFY_ROLE and I set it to MODERATOR 
but:
![Screen Shot 2020-06-06 at 16 23 02](https://user-images.githubusercontent.com/14811488/83945233-02519480-a812-11ea-8232-f99b8129df12.png)

**Comment by havfo** [comment]
The code for actually doing it has not been commited yet. Will soon arrive in a repository near you!

**Comment by havfo** [comment]
Code is live, please test, see 5a4bd1f
