### ISSUE TITLE
Sanitize the room name

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#499]
Room names == url path is not  sanitized and it cause problems

**Comment by misi** [comment]
Fixed express error handler to catch errors like "%" path caused for GARR. Still need to fix roomchooser

**Comment by edocod1** [comment]
Hello.
Instead of coming up with a custom solution, i'd suggest to use the excellent "unidecode" library, that converts unicode to ASCII meaningfully:
![image](https://user-images.githubusercontent.com/55318198/87428505-b77e2600-c5e2-11ea-97cd-e45cb6eff5e8.png)

https://www.npmjs.com/package/unidecode
