### ISSUE TITLE
sharing your screen popup auto hide

### ISSUE THREAD

**Issue by nullaegy** [edumeet/edumeet#565]
If I share my screen there is a default message:
<domain> is sharing your screen. [Stop sharing] [Hide]

It can be a little annoying, can you please make it autohide like 3-5 second or such? or at least save the last position? :) 
it's always in the way when I share a console, and it covers the commands what I type.

**Comment by Astagor** [comment]
This is a dialog from the browser, we don't have any influence on it as far as I know.

**Comment by nullaegy** [comment]
sad news :(  thanks anyway for checking. I'll dig deeper in chrome settings, maybe I can disable it somehow.

**Comment by misi** [comment]
Yes it is the chrome/framework of the browser notification (don't mix it with google chrome browser!!) 
and because screen share violates cross origin policy accordig w3c webrtc spec:

`
This feature has signficant security implications. Applications that use this API to access information that is displayed to users could access confidential information from other origins if that information is under the control of the application. This includes content that would otherwise be inaccessible due to the protections offered by the user agent sandbox. 
`

So spec here encourage browser vendors to add the mentioned warning:

`
User Agents are encouraged to warn users against sharing browser display devices as well as monitor display devices where browser windows are visible, or otherwise try to discourage their selection on the basis that these represent a significantly higher risk when shared.
`

See: 
https://www.w3.org/TR/screen-capture/

And so because of the big security risk I hardly think it will be not mandatory at all browsers!!

See for more human friendly not so dry details why it is so dangerous that notification is mandatory:

https://blog.mozilla.org/webrtc/share-browser-windows-entire-screen-sites-trust/
