### ISSUE TITLE
worker._routers is not iterable

### ISSUE THREAD

**Issue by Lenacus** [edumeet/edumeet#930]
I've updated (and cleaned) Edumeet 3.3 to 3.4.

Since, Edumeet don't start with errors. Any ideas ?

- process.env.DEBUG: edumeet*
- config.mediasoup.worker.logLevel: warn
- config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
  edumeet-server:WARN Auth is not configured properly! +0ms
  edumeet-server:INFO running 2 mediasoup Workers... +0ms
(node:292655) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
  edumeet-server:INFO connection request [roomId:"wamnyizw", peerId:"xadc9p0z"] +9s
  edumeet-server:INFO creating a new Room [roomId:"wamnyizw"] +1ms
  edumeet-server:INFO:Room create() [roomId:"wamnyizw"] +0ms
  edumeet-server:ERROR room creation or room joining failed [error:"TypeError: worker._routers is not iterable at Function.getLeastLoadedRouter (/usr/local/edumeet-3.4.0/server/lib/Room.js: 100: 32)
at Function.create (/usr/local/edumeet-3.4.0/server/lib/Room.js:215:49) at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async getOrCreateRoom (/usr/local/edumeet-3.4.0/server/server.js:809:10)
at async /usr/local/edumeet-3.4.0/server/server.js:693:17
at async AwaitQueue._runTask (/usr/local/edumeet-3.4.0/server/node_modules/awaitqueue/index.js:77:19)
at async AwaitQueue._next (/usr/local/edumeet-3.4.0/server/node_modules/awaitqueue/index.js:57:3)"]

**Comment by danisharora099** [comment]
This is because the current code for EduMeet makes use of private variables from the Mediasoup package; Mediasoup recently released a version update where they don't let you use their private vars and hence EduMeet will break for the people who are installing latest Mediasoup versions

I'll try to open a PR to fix these deprecated vars within this week; currently working on fixing the same on my own app :kek:
